import { TRIGGER_MORPH_DURATION } from "./motion";

// describe the collapsed trigger geometry used before the shell owns layout
export const EXPAND_FROM_TRIGGER_OPEN_DURATION = TRIGGER_MORPH_DURATION;
export const EXPAND_FROM_TRIGGER_CLOSE_DURATION = TRIGGER_MORPH_DURATION;
export const EXPAND_FROM_TRIGGER_COLLAPSED_HEIGHT = 50;
export const EXPAND_FROM_TRIGGER_COLLAPSED_BOTTOM_INSET = 2;
export const EXPAND_FROM_TRIGGER_COLLAPSED_HORIZONTAL_MARGIN = 28;
export const EXPAND_FROM_TRIGGER_COLLAPSED_FOOTER_INSET = 0;
export const EXPAND_FROM_TRIGGER_CONTENT_REVEAL_PROGRESS = 0.04;
